#!/usr/bin/env python3
"""
Gitskins-kit "Projects, live" tile generator for the xvviix profile.

Rebuilds gitskins/tiles/<repo>.svg — one themed 200x132 tile per live
GitHub Pages site — and rewrites the tile grid inside README.md
(between the GITSKINS:TILES markers) so the section always lists every
live site:

    * screenshot exists in screenshots/<repo>.jpg  -> tile embeds it
      (center-cropped to 184x97, JPEG q70, base64 in the SVG)
    * no screenshot yet                            -> themed placeholder
      tile (monogram + "github.io" caption)

Usage:  python3 gen_tiles.py        # needs Pillow

Data sources:
    * GitHub REST /users/xvviix/repos  (has_pages, homepage)
      (token from $GH_TOKEN, optional for public data)

Committed back to main by the gen-tiles workflow (hourly cron 30 * * * *).
"""
import base64
import io
import json
import os
import re
import time
import urllib.error
import urllib.request
import xml.dom.minidom
import xml.sax.saxutils

USER = "xvviix"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TILES = os.path.join(ROOT, "gitskins", "tiles")
SHOTS = os.path.join(ROOT, "screenshots")
README = os.path.join(ROOT, "README.md")

TOKEN = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
RAW = f"https://raw.githubusercontent.com/{USER}/{USER}/main"

FEATURED = "xvviix-portfolio"
INCLUDE_PLACEHOLDERS = True          # tiles for live sites without a screenshot

MARK_BEGIN = "<!-- GITSKINS:TILES:BEGIN (auto-generated by scripts/gen_tiles.py) -->"
MARK_END = "<!-- GITSKINS:TILES:END -->"

# Curated showcase order (current README grid). New live sites are appended
# after these, sorted by stars desc then name.
CURATED_ORDER = [
    "xvviix-portfolio", "aether", "sky-route", "ember-oak", "hearth-and-rye",
    "linden-apotheke", "aurea-dental", "sterling-longevity-clinic", "kai-lennox",
    "fitness-gym", "haven-property-rental", "mehrgan-realestate",
    "meridian-construction", "aether-architecture", "ashford-whitmore",
    "copperline-plumbing", "nail-salon", "Hair-salon", "iron-and-velvet",
    "atelier-linnea", "aurelle-ritual-bathing-house", "eila-yoga-studio",
    "jewelry-store", "Perfume", "Habibi-shoes", "zarineh-watch-store",
    "Dastin", "photography-portfolio", "travel-agency", "Freshmart",
    "aurelian-university", "Human-life", "ferdows-grand-hotel", "eclat",
    "forma-os", "voltaic-engineering", "chrona-bio", "aevum-cloud",
    "lajevard-tea-house", "nova-mobile-gallery", "ketabnegar-bookstore",
    "hirkan-luxury-camping", "volt-gaming-store", "sedra-premium",
    "aryabar-logistics", "azarcan.github.io",
]

# Nice titles for tile labels / tooltips (current README titles).
DISPLAY = {
    "xvviix-portfolio": "XVVIIX Portfolio",
    "aether": "Aether AI Platform",
    "sky-route": "SkyRoute Airlines",
    "ember-oak": "Ember & Oak — Coffee",
    "hearth-and-rye": "Hearth & Rye — Bakery",
    "linden-apotheke": "Linden Apotheke",
    "aurea-dental": "Auréa Dental",
    "sterling-longevity-clinic": "Sterling Longevity Clinic",
    "kai-lennox": "Kai Lennox",
    "fitness-gym": "Apexfit Gym",
    "haven-property-rental": "Haven Property Rental",
    "mehrgan-realestate": "Mehrgan Real Estate",
    "meridian-construction": "Meridian Construction",
    "aether-architecture": "AETHER Architecture",
    "ashford-whitmore": "Ashford & Whitmore",
    "copperline-plumbing": "Copperline Plumbing",
    "nail-salon": "LUMIÈRE Nail Atelier",
    "Hair-salon": "Hair Salon",
    "iron-and-velvet": "Iron & Velvet Barbershop",
    "atelier-linnea": "Atelier Linnea",
    "aurelle-ritual-bathing-house": "Aurelle Ritual Bathing",
    "eila-yoga-studio": "Eila Yoga Studio",
    "jewelry-store": "LUMEN Jewelry",
    "Perfume": "Royal Perfume",
    "Habibi-shoes": "Habibi Shoes",
    "zarineh-watch-store": "Zarineh Watches",
    "Dastin": "Dastin Brand",
    "photography-portfolio": "Photography Portfolio",
    "travel-agency": "Auora Voyages",
    "Freshmart": "Freshmart",
    "aurelian-university": "Aurelian University",
    "Human-life": "Human Life",
    "ferdows-grand-hotel": "Ferdows Grand Hotel",
    "eclat": "ÉCLAT Flower Atelier",
    "forma-os": "FORMA OS",
    "voltaic-engineering": "Voltaic Engineering",
    "chrona-bio": "CHRONA Bio",
    "aevum-cloud": "Aevum Cloud",
    "lajevard-tea-house": "چایخانهٔ لاجورد",
    "nova-mobile-gallery": "NOVA Mobile Gallery",
    "ketabnegar-bookstore": "کتاب‌نگار",
    "hirkan-luxury-camping": "هیرکان کمپینگ",
    "volt-gaming-store": "VOLT Gaming",
    "sedra-premium": "Sedra Premium",
    "aryabar-logistics": "آریابار لجستیک",
    "azarcan.github.io": "آذرکَن — Lighting House",
}


def e(text) -> str:
    return xml.sax.saxutils.escape(str(text), {'"': "&quot;"})


def _http(url: str, headers: dict = None, retries: int = 3) -> bytes:
    hdrs = {"User-Agent": "xvviix-profile-gen/1.0"}
    if TOKEN:
        hdrs["Authorization"] = "Bearer " + TOKEN
    if headers:
        hdrs.update(headers)
    last = None
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers=hdrs)
            with urllib.request.urlopen(req, timeout=30) as r:
                return r.read()
        except urllib.error.HTTPError as ex:
            last = ex
            if ex.code in (403, 429) and i < retries - 1:
                ra = ex.headers.get("Retry-After")
                time.sleep(int(ra) if (ra or "").isdigit() else 8 * (i + 1))
                continue
            try:
                body = ex.read()[:200]
            except Exception:
                body = b""
            raise RuntimeError(
                f"HTTP {ex.code} for {url} (token={'yes' if TOKEN else 'no'}): {body!r}"
            ) from ex
        except Exception as ex:
            last = ex
            if i < retries - 1:
                time.sleep(4 * (i + 1))
                continue
            raise
    raise RuntimeError(f"HTTP fail for {url}: {last}")


def shot_to_b64(path: str) -> str:
    """Center-crop screenshot to 184:97, resize, re-encode JPEG q70, base64."""
    from PIL import Image
    im = Image.open(path).convert("RGB")
    tw, th = 184, 97
    ratio = tw / th
    w, h = im.size
    if w / h > ratio:
        nw = int(h * ratio)
        im = im.crop(((w - nw) // 2, 0, (w + nw) // 2, h))
    else:
        nh = int(w / ratio)
        im = im.crop((0, (h - nh) // 2, w, (h + nh) // 2))
    im = im.resize((tw, th), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=70, optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


def display_name(repo: dict) -> str:
    name = repo["name"]
    if name in DISPLAY:
        return DISPLAY[name]
    stem = name[:-10] if name.endswith(".github.io") else name
    return re.sub(r"[-_]+", " ", stem).strip().title() or name


def site_url(repo: dict) -> str:
    name = repo["name"]
    hp = (repo.get("homepage") or "").strip()
    if hp:
        if not hp.startswith("http"):
            hp = "https://" + hp
        return hp if hp.endswith("/") else hp + "/"
    if name.endswith(".github.io"):          # user site repo
        return f"https://{USER}.github.io/"
    return f"https://{USER}.github.io/{name}/"


def render_tile(repo: dict, b64: str = None) -> str:
    name = repo["name"]
    disp = display_name(repo)
    featured = name == FEATURED
    border = "#d4af37" if featured else "#2dd4bf"
    dot = "#f0d070" if featured else "#4ade80"
    tag = "★ FEATURED" if featured else "LIVE"
    pfx = f"t-{re.sub(r'[^a-zA-Z0-9]', '-', name)}"

    if b64:
        shot = (
            f'  <g clip-path="url(#{pfx}-clip)">\n'
            f'    <image href="data:image/jpeg;base64,{b64}" x="8" y="8" width="184" '
            f'height="97" preserveAspectRatio="xMidYMid slice"/>\n'
            f"  </g>\n"
        )
    else:
        shot = (
            f'  <g clip-path="url(#{pfx}-clip)">\n'
            f'    <rect x="8" y="8" width="184" height="97" fill="url(#{pfx}-ph)"/>\n'
            f'    <rect x="8" y="8" width="184" height="97" fill="url(#{pfx}-grid)"/>\n'
            f'    <text x="100" y="64" text-anchor="middle" font-family="ui-monospace,'
            f'SFMono-Regular,Menlo,monospace" font-size="30" font-weight="800" '
            f'fill="{border}" opacity="0.85">{e(disp[:1])}</text>\n'
            f'    <text x="100" y="86" text-anchor="middle" font-family="ui-monospace,'
            f'SFMono-Regular,Menlo,monospace" font-size="8.5" letter-spacing="1.4" '
            f'fill="#5eead4" opacity="0.75">GITHUB.IO</text>\n'
            f"  </g>\n"
        )

    ph_defs = ""
    if not b64:
        ph_defs = (
            f'    <linearGradient id="{pfx}-ph" x1="0" y1="0" x2="1" y2="1">\n'
            f'      <stop offset="0%" stop-color="#0b2f2c"/>\n'
            f'      <stop offset="100%" stop-color="#061a19"/>\n'
            f"    </linearGradient>\n"
            f'    <pattern id="{pfx}-grid" width="16" height="16" patternUnits="userSpaceOnUse">\n'
            f'      <path d="M 16 0 L 0 0 0 16" fill="none" stroke="#2dd4bf" '
            f'stroke-opacity="0.10" stroke-width="0.6"/>\n'
            f"    </pattern>\n"
        )

    label = disp if len(disp) <= 22 else disp[:21] + "…"
    body = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="132" viewBox="0 0 200 132" role="img" aria-label="{e(disp)} — live site">
  <defs>
    <linearGradient id="{pfx}-bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#042f2e"/>
      <stop offset="55%" stop-color="#0c3a37"/>
      <stop offset="100%" stop-color="#042f2e"/>
    </linearGradient>
{ph_defs}    <clipPath id="{pfx}-clip"><rect x="8" y="8" width="184" height="97" rx="8"/></clipPath>
  </defs>
  <rect x="0.5" y="0.5" width="199" height="131" rx="12" fill="url(#{pfx}-bg)" stroke="{border}" stroke-opacity="0.62"/>
{shot}  <rect x="8.5" y="8.5" width="183" height="96" rx="7.5" fill="none" stroke="#ccfbf1" stroke-opacity="0.16"/>
  <text x="10" y="123" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="10.5" font-weight="700" fill="#ccfbf1">{e(label)}</text>
  <circle cx="160" cy="119.5" r="3" fill="{dot}">
    <animate attributeName="opacity" values="1;0.3;1" dur="1.6s" repeatCount="indefinite"/>
  </circle>
  <text x="190" y="123" text-anchor="end" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="8" font-weight="800" letter-spacing="1" fill="{dot}">{tag}</text>
  <rect x="0.5" y="0.5" width="199" height="131" rx="11.5" fill="none" stroke="{border}" stroke-opacity="0.35"/>
</svg>
'''
    return body


def build_grid(tiles: list) -> str:
    lines = ['<div align="center">']
    for t in tiles:
        lines.append(
            f'<a href="{t["url"]}"><img src="{RAW}/gitskins/tiles/{t["name"]}.svg" '
            f'width="200" title="{e(t["disp"])}" alt="{e(t["disp"])}"/></a>'
        )
    lines.append("</div>")
    return "\n".join(lines)


def main():
    # ---- fetch live pages repos (with Link header pagination) ----
    url = f"/users/{USER}/repos?per_page=100&type=owner"
    repos = []
    while url:
        hdrs = {"User-Agent": "xvviix-profile-gen/1.0"}
        if TOKEN:
            hdrs["Authorization"] = "Bearer " + TOKEN
        req = urllib.request.Request("https://api.github.com" + url, headers=hdrs)
        with urllib.request.urlopen(req, timeout=30) as r:
            repos.extend(json.loads(r.read()))
            m = re.search(r'<([^>]+)>;\s*rel="next"', r.headers.get("Link", ""))
            url = m.group(1) if m else None

    pages = [r for r in repos if r.get("has_pages")]
    if not pages:
        raise SystemExit("no has_pages repos — refusing to wipe the section")

    by_name = {r["name"]: r for r in pages}
    order = [n for n in CURATED_ORDER if n in by_name]
    rest = sorted(
        (r for r in pages if r["name"] not in CURATED_ORDER),
        key=lambda r: (-r.get("stargazers_count") or 0, r["name"].lower()),
    )
    order += [r["name"] for r in rest]

    os.makedirs(TILES, exist_ok=True)
    tiles, written, placeholder_n = [], 0, 0
    for name in order:
        repo = by_name[name]
        disp = display_name(repo)
        b64 = None
        shot = os.path.join(SHOTS, name + ".jpg")
        if not os.path.exists(shot):
            shot = os.path.join(SHOTS, name + ".png")
        if os.path.exists(shot):
            b64 = shot_to_b64(shot)
        elif not INCLUDE_PLACEHOLDERS:
            continue
        else:
            placeholder_n += 1
        svg = render_tile(repo, b64)
        xml.dom.minidom.parseString(svg)          # validate before writing
        path = os.path.join(TILES, name + ".svg")
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != svg:
            with open(path, "w", encoding="utf-8") as f:
                f.write(svg)
            written += 1
        tiles.append({"name": name, "disp": disp, "url": site_url(repo)})

    # drop tiles for repos that lost Pages
    for f in os.listdir(TILES):
        if f.endswith(".svg") and f[:-4] not in by_name:
            os.remove(os.path.join(TILES, f))
            print("removed stale tile:", f)

    # ---- update README grid between markers ----
    readme = open(README, encoding="utf-8").read()
    grid = build_grid(tiles)
    new = re.sub(
        re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
        MARK_BEGIN + "\n" + grid + "\n" + MARK_END,
        readme, flags=re.S,
    )
    if new != readme:
        with open(README, "w", encoding="utf-8") as f:
            f.write(new)
        print("README grid updated")
    else:
        print("README grid unchanged")

    print(f"{len(tiles)} live sites ({len(tiles) - placeholder_n} with shot, "
          f"{placeholder_n} placeholder) — {written} tile file(s) written")


if __name__ == "__main__":
    main()
