#!/usr/bin/env python3
"""Social card: clickable via the PROVEN tile pattern.

GitHub strips inline <svg> from profile READMEs (the markup shows up as
escaped text), and <img src="*.svg"> is a flat picture (nothing inside it is
clickable). The only pattern that definitely works is what the "Projects,
live" grid uses: <a href="..."><img src="*.svg"/></a>.

So each social chip is its own small SVG (same aurora-dark kit styling) and
the README lays them out in one centered row:

  [github (a>img)] [email (a>img)] [telegram (a>img)]

  github  -> https://github.com/xvviix
  email   -> mailto:matinhabibi688@gmail.com
  telegram-> https://t.me/xvviix

The "What I build" section was removed from the profile; this script no
longer manages it.

Re-running is idempotent: the README block between the GITSKINS:SOCIAL
markers is regenerated.
"""
import html
import os
import re
import sys

USER = "xvviix"
RAW = f"https://raw.githubusercontent.com/{USER}/{USER}/main/gitskins"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
README = os.path.join(ROOT, "README.md")
SOC_DIR = os.path.join(ROOT, "gitskins", "social-chips")

SOC_MARK = "<!-- GITSKINS:SOCIAL:BEGIN (auto-generated by scripts/make_clickable.py) -->"
SOC_END = "<!-- GITSKINS:SOCIAL:END -->"

FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"

BG = """<linearGradient id="c-bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#042f2e"/>
      <stop offset="55%" stop-color="#0c3a37"/>
      <stop offset="100%" stop-color="#042f2e"/>
    </linearGradient>"""


def esc(s):
    return html.escape(s, quote=False)


def social_chip(kind):
    """Chip design, each on its own background strip."""
    if kind == "github":
        w, h = 178, 46
        inner = f'''<circle cx="27" cy="23" r="12" fill="#ffffff" fill-opacity="0.16"/>
  <text x="27" y="28" font-family="{FONT}" font-size="13" font-weight="900" fill="#ffffff" text-anchor="middle">G</text>
  <text x="48" y="19" font-family="{FONT}" font-size="10" font-weight="850" letter-spacing="1.2" fill="#5eead4">GitHub</text>
  <text x="48" y="35" font-family="{FONT}" font-size="13" font-weight="800" fill="#ccfbf1">@xvviix</text>'''
    elif kind == "email":
        w, h = 252, 46
        inner = f'''<circle cx="27" cy="23" r="12" fill="#ffffff" fill-opacity="0.16"/>
  <text x="27" y="28" font-family="{FONT}" font-size="14" font-weight="900" fill="#ffffff" text-anchor="middle">@</text>
  <text x="48" y="19" font-family="{FONT}" font-size="10" font-weight="850" letter-spacing="1.2" fill="#5eead4">Email</text>
  <text x="48" y="35" font-family="{FONT}" font-size="13" font-weight="800" fill="#ccfbf1">matinhabibi688@gmail.com</text>'''
    else:
        w, h = 170, 46
        inner = f'''<circle cx="27" cy="23" r="12" fill="#ffffff" fill-opacity="0.16"/>
  <path d="M 20 29 L 35 23 L 20 17 L 20 21 L 28 23 L 20 25 Z" fill="#ffffff" fill-opacity="0.92"/>
  <text x="48" y="19" font-family="{FONT}" font-size="10" font-weight="850" letter-spacing="1.2" fill="#5eead4">Telegram</text>
  <text x="48" y="35" font-family="{FONT}" font-size="13" font-weight="800" fill="#ccfbf1">t.me/xvviix</text>'''
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{kind}">
  <defs>{BG}</defs>
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="22" fill="url(#c-bg)" stroke="#2dd4bf" stroke-opacity="0.62"/>
  <rect x="1.5" y="1.5" width="{w-3}" height="{h-3}" rx="21" fill="none" stroke="#ffffff" stroke-opacity="0.14"/>
  {inner}
</svg>
'''


def install_readme(section, block, img_fallback):
    """Replace the GITSKINS:<section> marker block (any variant) or, on first
    run, the legacy <img> block."""
    cur = open(README, encoding="utf-8").read()
    pat = re.compile(
        r"<!-- GITSKINS:" + section + r":BEGIN[^>]*-->.*?"
        r"<!-- GITSKINS:" + section + r":END -->", re.S)
    if pat.search(cur):
        cur = pat.sub(lambda _m: block, cur, count=1)
    else:
        if not img_fallback.search(cur):
            sys.exit(f"README: neither marker block nor <img> fallback found for {section!r}")
        cur = img_fallback.sub(lambda _m: block, cur, count=1)
    open(README, "w", encoding="utf-8").write(cur)
    print(f"README: {section} block installed")


def main():
    os.makedirs(SOC_DIR, exist_ok=True)
    for kind in ("github", "email", "telegram"):
        open(os.path.join(SOC_DIR, f"{kind}.svg"), "w", encoding="utf-8").write(social_chip(kind))
    print("wrote 3 social chips")

    soc_lines = [SOC_MARK, '<div align="center">',
                 f'<a href="https://github.com/{USER}">'
                 f'<img src="{RAW}/social-chips/github.svg" width="178" height="46" alt="GitHub"/></a>',
                 '<a href="mailto:matinhabibi688@gmail.com">'
                 f'<img src="{RAW}/social-chips/email.svg" width="252" height="46" alt="Email"/></a>',
                 f'<a href="https://t.me/{USER}">'
                 f'<img src="{RAW}/social-chips/telegram.svg" width="170" height="46" alt="Telegram"/></a>',
                 "</div>", SOC_END]
    soc_block = "\n".join(soc_lines)
    soc_img = re.compile(
        r'<p align="center">\s*'
        r'<img src="https://raw\.githubusercontent\.com/xvviix/xvviix/main/gitskins/social\.svg"[^>]*/>\s*'
        r'</p>')
    install_readme("SOCIAL", soc_block, soc_img)
    print("done.")


if __name__ == "__main__":
    main()
