#!/usr/bin/env python3
"""What-I-Build + Social: clickable via the PROVEN tile pattern.

GitHub strips inline <svg> from profile READMEs (the markup shows up as
escaped text). The only clickable pattern that definitely works is what the
"Projects, live" grid uses: <a href="..."><img src="*.svg"/></a>.

So each site chip and each social chip becomes its own small SVG (same
aurora-dark kit styling) and the README lays them out per category:

  title strip (img)
  [category pill (img)] [chip (a>img)] [chip (a>img)] ...   <- wraps naturally
  ...
  footer strip (a>img -> repos tab)

  social: [github (a>img)] [email (a>img)] [telegram (a>img)]

Re-running is idempotent: everything is rewritten and the README blocks
between the GITSKINS:WIB / GITSKINS:SOCIAL markers are regenerated.
"""
import html
import json
import os
import re
import sys
import urllib.request

USER = "xvviix"
RAW = f"https://raw.githubusercontent.com/{USER}/{USER}/main/gitskins"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
README = os.path.join(ROOT, "README.md")
WIB_DIR = os.path.join(ROOT, "gitskins", "wib")
SOC_DIR = os.path.join(ROOT, "gitskins", "social-chips")

WIB_MARK = "<!-- GITSKINS:WIB:BEGIN (auto-generated by scripts/make_clickable.py) -->"
WIB_END = "<!-- GITSKINS:WIB:END -->"
SOC_MARK = "<!-- GITSKINS:SOCIAL:BEGIN (auto-generated by scripts/make_clickable.py) -->"
SOC_END = "<!-- GITSKINS:SOCIAL:END -->"

FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"
MONO = "ui-monospace,SFMono-Regular,Menlo,monospace"

# (emoji, category name) in order — matches the rows of gitskins/what-i-build.svg
CATEGORIES = [
    ("⚡", "AI & Platforms"),
    ("🎓", "Education"),
    ("🏗️", "Construction & Real Estate"),
    ("☕", "Food, Coffee & Hospitality"),
    ("🇮🇷", "Persian sites"),
    ("💈", "Salons, Style & Beauty"),
    ("🏥", "Health, Wellness & Services"),
    ("🎮", "Games & Desktop"),
    ("🎨", "Portfolios & Brands"),
    ("🐍", "Python Apps"),
]

BG = """<linearGradient id="c-bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#042f2e"/>
      <stop offset="55%" stop-color="#0c3a37"/>
      <stop offset="100%" stop-color="#042f2e"/>
    </linearGradient>"""


def esc(s):
    return html.escape(s, quote=False)


def fetch_wib_rows():
    """Parse rows (category + [(repo, label)]) from gitskins/what-i-build.svg."""
    svg = open(os.path.join(ROOT, "gitskins", "what-i-build.svg"), encoding="utf-8").read()
    rows = []
    for m in re.finditer(r'<g class="wib-row"[^>]*>(.*?)</g>', svg, re.S):
        body = m.group(1)
        name_m = re.search(
            r'<text x="84" y="[\d.]+" font-family="[^"]*" font-size="12" '
            r'font-weight="800"[^>]*>([^<]+)</text>', body)
        chips = []
        for a in re.finditer(
                r'<a href="https://github\.com/' + USER + r'/([^"]+)">'
                r'<title>([^<]+)</title>', body):
            chips.append((a.group(1), html.unescape(a.group(2))))
        rows.append((html.unescape(name_m.group(1)), chips))
    if len(rows) != len(CATEGORIES):
        sys.exit(f"expected {len(CATEGORIES)} wib rows, parsed {len(rows)}")
    return rows


def chip_svg(repo, label):
    name = label if len(label) <= 17 else label[:16] + "…"
    w = min(178, max(92, 74 + int(len(name) * 6.6)))
    h = 44
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{esc(label)} — open repo">
  <defs>{BG}</defs>
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="11" fill="url(#c-bg)" stroke="#2dd4bf" stroke-opacity="0.45"/>
  <circle cx="22" cy="{h/2}" r="12" fill="#ffffff" fill-opacity="0.14"/>
  <text x="22" y="{h/2+4.5}" font-family="{FONT}" font-size="13" font-weight="900" fill="#ffffff" text-anchor="middle">{esc(name[0].upper())}</text>
  <text x="42" y="{h/2+4}" font-family="{MONO}" font-size="11" font-weight="700" fill="#ccfbf1">{esc(name)}</text>
  <circle cx="{w-13}" cy="{h/2}" r="2.6" fill="#4ade80">
    <animate attributeName="opacity" values="1;0.3;1" dur="1.6s" repeatCount="indefinite"/>
  </circle>
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="10.5" fill="none" stroke="#ccfbf1" stroke-opacity="0.10"/>
</svg>
'''


def cat_svg(emoji, name):
    w = int(30 + len(name) * 6.6) + 24
    h = 32
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{esc(name)}">
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="16" fill="rgba(8,8,12,0.55)" stroke="#2dd4bf" stroke-opacity="0.35"/>
  <text x="16" y="{h/2+5.5}" font-size="14">{emoji}</text>
  <text x="40" y="{h/2+4.5}" font-family="{FONT}" font-size="12" font-weight="800" letter-spacing="0.2" fill="#ccfbf1">{esc(name)}</text>
</svg>
'''


def title_svg():
    w, h = 860, 92
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="What I build">
  <defs>{BG}
    <radialGradient id="t-orb-0" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#2dd4bf" stop-opacity="0.55"/>
      <stop offset="58%" stop-color="#2dd4bf" stop-opacity="0.14"/>
      <stop offset="100%" stop-color="#2dd4bf" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="t-orb-1" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#a78bfa" stop-opacity="0.4"/>
      <stop offset="58%" stop-color="#a78bfa" stop-opacity="0.12"/>
      <stop offset="100%" stop-color="#a78bfa" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="{w}" height="{h}" rx="20" fill="url(#c-bg)"/>
  <ellipse cx="150" cy="14" rx="230" ry="80" fill="url(#t-orb-0)"/>
  <ellipse cx="760" cy="80" rx="220" ry="75" fill="url(#t-orb-1)"/>
  <text x="46" y="45" font-family="{FONT}" font-size="28" font-weight="850" letter-spacing="-0.5" fill="#ccfbf1">What I build</text>
  <text x="48" y="68" font-family="{FONT}" font-size="13" font-weight="650" letter-spacing="1.2" fill="#5eead4">Premium static sites — designed from scratch · click a site to open its repo</text>
  <rect x="644" y="26" width="170" height="34" rx="17" fill="rgba(45,212,191,0.1)" stroke="#2dd4bf" stroke-opacity="0.5"/>
  <text x="729" y="47.5" text-anchor="middle" font-family="{MONO}" font-size="10.5" font-weight="800" letter-spacing="1" fill="#5eead4">100% STATIC · 0 DEPS</text>
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="19.5" fill="none" stroke="#2dd4bf" stroke-opacity="0.62"/>
</svg>
'''


def footer_svg():
    w, h = 860, 54
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="view all repositories">
  <defs>{BG}</defs>
  <rect width="{w}" height="{h}" rx="20" fill="url(#c-bg)"/>
  <line x1="46" y1="12" x2="814" y2="12" stroke="#2dd4bf" stroke-opacity="0.22" stroke-dasharray="4 7"/>
  <text x="46" y="40" font-family="{FONT}" font-size="12" font-weight="650" letter-spacing="0.3" fill="#5eead4" opacity="0.85">100% static · zero frameworks · zero dependencies — every site ships as-is</text>
  <text x="814" y="40" text-anchor="end" font-family="{MONO}" font-size="10.5" font-weight="700" letter-spacing="0.5" fill="#f5d061" opacity="0.9">view all repos ↗</text>
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="19.5" fill="none" stroke="#2dd4bf" stroke-opacity="0.62"/>
</svg>
'''


def social_chip(kind):
    """Exact chip designs from gitskins/social.svg, each on its own background."""
    if kind == "github":
        w, h = 178, 46
        inner = f'''<circle cx="27" cy="23" r="12" fill="#ffffff" fill-opacity="0.16"/>
  <text x="27" y="28" font-family="{FONT}" font-size="13" font-weight="900" fill="#ffffff" text-anchor="middle">G</text>
  <text x="48" y="19" font-family="{FONT}" font-size="10" font-weight="850" letter-spacing="1.2" fill="#5eead4">GitHub</text>
  <text x="48" y="35" font-family="{FONT}" font-size="13" font-weight="800" fill="#ccfbf1">@xvviix</text>'''
    elif kind == "email":
        w, h = 252, 46
        inner = f'''<circle cx="27" cy="23" r="12" fill="#ffffff" fill-opacity="0.16"/>
  <text x="27" y="28" font-family="{FONT}" font-size="14" font-weight="900" fill="#ffffff" text-anchor="middle">@</text>
  <text x="48" y="19" font-family="{FONT}" font-size="10" font-weight="850" letter-spacing="1.2" fill="#5eead4">Email</text>
  <text x="48" y="35" font-family="{FONT}" font-size="13" font-weight="800" fill="#ccfbf1">matinhabibi688@gmail.com</text>'''
    else:
        w, h = 170, 46
        inner = f'''<circle cx="27" cy="23" r="12" fill="#ffffff" fill-opacity="0.16"/>
  <path d="M 20 29 L 35 23 L 20 17 L 20 21 L 28 23 L 20 25 Z" fill="#ffffff" fill-opacity="0.92"/>
  <text x="48" y="19" font-family="{FONT}" font-size="10" font-weight="850" letter-spacing="1.2" fill="#5eead4">Telegram</text>
  <text x="48" y="35" font-family="{FONT}" font-size="13" font-weight="800" fill="#ccfbf1">t.me/xvviix</text>'''
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{kind}">
  <defs>{BG}</defs>
  <rect x="0.5" y="0.5" width="{w-1}" height="{h-1}" rx="22" fill="url(#c-bg)" stroke="#2dd4bf" stroke-opacity="0.62"/>
  <rect x="1.5" y="1.5" width="{w-3}" height="{h-3}" rx="21" fill="none" stroke="#ffffff" stroke-opacity="0.14"/>
  {inner}
</svg>
'''


def install_readme(section, block, img_fallback):
    """Replace the GITSKINS:<section> marker block (any variant) or, on first
    run, the legacy <img> block."""
    cur = open(README, encoding="utf-8").read()
    pat = re.compile(
        r"<!-- GITSKINS:" + section + r":BEGIN[^>]*-->.*?"
        r"<!-- GITSKINS:" + section + r":END -->", re.S)
    if pat.search(cur):
        cur = pat.sub(lambda _m: block, cur, count=1)
    else:
        if not img_fallback.search(cur):
            sys.exit(f"README: neither marker block nor <img> fallback found for {section!r}")
        cur = img_fallback.sub(lambda _m: block, cur, count=1)
    open(README, "w", encoding="utf-8").write(cur)
    print(f"README: {section} block installed")


def main():
    os.makedirs(WIB_DIR, exist_ok=True)
    os.makedirs(SOC_DIR, exist_ok=True)

    rows = fetch_wib_rows()

    # ---- assets ----
    open(os.path.join(WIB_DIR, "title.svg"), "w", encoding="utf-8").write(title_svg())
    open(os.path.join(WIB_DIR, "footer.svg"), "w", encoding="utf-8").write(footer_svg())
    for i, (emoji, _name) in enumerate(CATEGORIES, 1):
        open(os.path.join(WIB_DIR, f"cat-{i}.svg"), "w", encoding="utf-8").write(
            cat_svg(emoji, rows[i - 1][0]))
    n = 0
    for _cat, chips in rows:
        for repo, label in chips:
            open(os.path.join(WIB_DIR, f"chip-{repo}.svg"), "w", encoding="utf-8").write(
                chip_svg(repo, label))
            n += 1
    for kind in ("github", "email", "telegram"):
        open(os.path.join(SOC_DIR, f"{kind}.svg"), "w", encoding="utf-8").write(social_chip(kind))
    print(f"wrote title, footer, {len(CATEGORIES)} category pills, {n} chips, 3 social chips")

    # ---- README: what i build ----
    lines = [WIB_MARK, '<div align="center">',
             f'<img src="{RAW}/wib/title.svg" alt="What I build — project catalog by industry" width="860"/>',
             "<br/>"]
    for i, (_emoji, _name) in enumerate(CATEGORIES, 1):
        _cat, chips = rows[i - 1]
        lines.append('<div>')
        lines.append(f'<img src="{RAW}/wib/cat-{i}.svg" height="32" alt="{esc(_name)}"/>')
        for repo, label in chips:
            w = min(178, max(92, 74 + int(len((label if len(label) <= 17 else label[:16] + "…")) * 6.6)))
            lines.append(
                f'<a href="https://github.com/{USER}/{repo}">'
                f'<img src="{RAW}/wib/chip-{repo}.svg" width="{w}" height="44" '
                f'title="{esc(label)} — repo" alt="{esc(label)}"/></a>')
        lines.append("</div>")
    lines += ["<br/>",
              f'<a href="https://github.com/{USER}?tab=repositories">'
              f'<img src="{RAW}/wib/footer.svg" alt="view all repositories" width="860"/></a>',
              "</div>", WIB_END]
    wib_block = "\n".join(lines)
    wib_img = re.compile(
        r'<p align="center">\s*'
        r'(?:<a href="https://github\.com/xvviix\?tab=repositories">\s*)?'
        r'<img src="https://raw\.githubusercontent\.com/xvviix/xvviix/main/gitskins/what-i-build\.svg"[^>]*/>\s*'
        r'(?:</a>\s*)?</p>')
    install_readme("WIB", wib_block, wib_img)

    # ---- README: social ----
    soc_lines = [SOC_MARK, '<div align="center">',
                 f'<a href="https://github.com/{USER}">'
                 f'<img src="{RAW}/social-chips/github.svg" width="178" height="46" alt="GitHub"/></a>',
                 '<a href="mailto:matinhabibi688@gmail.com">'
                 f'<img src="{RAW}/social-chips/email.svg" width="252" height="46" alt="Email"/></a>',
                 f'<a href="https://t.me/{USER}">'
                 f'<img src="{RAW}/social-chips/telegram.svg" width="170" height="46" alt="Telegram"/></a>',
                 "</div>", SOC_END]
    soc_block = "\n".join(soc_lines)
    soc_img = re.compile(
        r'<p align="center">\s*'
        r'<img src="https://raw\.githubusercontent\.com/xvviix/xvviix/main/gitskins/social\.svg"[^>]*/>\s*'
        r'</p>')
    install_readme("SOCIAL", soc_block, soc_img)
    print("done.")


if __name__ == "__main__":
    main()
